import { ObjectType } from '../../types/mathTypes';
import { MathInput } from '../../types/mathObjectSettingsInterfaces';
import { IdBuilder } from '../utils/builders/id/IdBuilder';
import { NameBuilder } from '../utils/builders/name/NameBuilder';
import { PromptBuilder } from '../utils/builders/prompt/PromptBuilder';
import { ComplexityBuilder } from '../utils/builders/complexity/ComplexityBuilder';

/**
 * The base abstract class for all test cases. Defines the common interface and
 * properties that specialized test case implementations must adhere to.
 * Test cases encapsulate the necessary information to generate a specific mathematical object
 * or scenario for testing purposes.
 *
 * @template S - The type of the settings object used to configure this test case.
 *             Must be a record-like type (object with string keys).
 */
export abstract class TestCase<S extends Record<string, unknown>> {
    // Core test properties
    /**
     * A descriptive name for the test case. Generated by `buildName`.
     */
    public name: string = '';
    /**
     * The prompt or instructions associated with the test case. Generated by `buildPrompt`.
     */
    public prompt: string = '';
    /**
     * The type of mathematical object this test case is designed for (e.g., Equation, Function).
     */
    public objectType: ObjectType;
    /**
     * A unique identifier for this specific test instance. Generated by `buildTestId`.
     */
    public testId: string = '';
    /**
     * The category or generator type that produced this test case. Set via `setCategory`.
     */
    public category: string = '';
    
    // Optional properties
    /**
     * An optional score representing the calculated complexity of the test case.
     * Calculated by `calculateComplexity`.
     */
    public complexityScore?: number;
    /**
     * An optional metric indicating the success rate for this test case (e.g., from past runs).
     * Not currently calculated or set by the base class.
     */
    public successRate?: number;
    /**
     * An optional numerical value associated with the test case, its meaning depends on the context.
     * Not currently calculated or set by the base class.
     */
    public value?: number;
    /**
     * An optional list of related mathematical items or identifiers.
     * Not currently calculated or set by the base class.
     */
    public mathItems?: string[];
    
    // Settings that configure this test case
    /**
     * The configuration settings used to generate this test case. Stored internally.
     * Access via `getSettings`.
     * @protected
     */
    protected settings: Partial<S>;
    
    // Builders
    /**
     * Optional builder for generating the test case ID.
     * @protected
     */
    protected idBuilder?: IdBuilder<S>;
    /**
     * Optional builder for generating the test case name.
     * @protected
     */
    protected nameBuilder?: NameBuilder<S>;
    /**
     * Optional builder for generating the test case prompt.
     * @protected
     */
    protected promptBuilder?: PromptBuilder<S>;
    /**
     * Optional builder for calculating the test case complexity.
     * @protected
     */
    protected complexityBuilder?: ComplexityBuilder<S>;
    
    /**
     * Creates an instance of TestCase.
     * @param objectType The type of mathematical object this test case targets.
     * @param settings An optional partial settings object to configure the test case generation. Defaults to an empty object.
     */
    constructor(objectType: ObjectType, settings: Partial<S> = {}) {
        this.objectType = objectType;
        this.settings = settings;
    }

    /**
     * Generates the core properties of the test case (name, prompt, complexity, testId)
     * by calling the respective builder methods or requiring subclass implementation.
     * This method should be called after the constructor and any necessary builder setup.
     */
    public generate(): void {
        this.name = this.buildName();
        this.prompt = this.buildPrompt();
        this.complexityScore = this.calculateComplexity();
        this.testId = this.buildTestId();
    }

    /**
     * Sets the category of the test case. This is typically called by the generator
     * that creates the test case instance.
     * @param category The category name (e.g., 'simple', 'boundary', 'random').
     */
    public setCategory(category: string): void {
        this.category = category;
    }

    /**
     * Retrieves a shallow copy of the settings object used for this test case.
     * @returns A copy of the `settings` object.
     */
    public getSettings(): Partial<S> {
        return { ...this.settings };
    }

    /**
     * Builds a formatted, descriptive name for the test case based on its settings.
     * Uses the configured `nameBuilder` if available.
     * If no `nameBuilder` is provided, subclasses *must* override this method.
     * @returns The generated name string.
     * @throws {Error} If no `nameBuilder` is provided and the method is not overridden by the subclass.
     * @protected
     */
    protected buildName(): string {
        if (this.nameBuilder) {
            return this.nameBuilder.build(this.settings);
        }
        
        // For backward compatibility
        throw new Error(`buildName must be implemented by the subclass or a nameBuilder must be provided`);
    }
    
    /**
     * Builds the prompt or instruction text for the test case based on its settings.
     * Uses the configured `promptBuilder` if available.
     * If no `promptBuilder` is provided, subclasses *must* override this method.
     * @returns The generated prompt string.
     * @throws {Error} If no `promptBuilder` is provided and the method is not overridden by the subclass.
     * @protected
     */
    protected buildPrompt(): string {
        if (this.promptBuilder) {
            return this.promptBuilder.build(this.settings);
        }
        
        // For backward compatibility
        throw new Error(`buildPrompt must be implemented by the subclass or a promptBuilder must be provided`);
    }
    
    /**
     * Builds a unique identifier for this test case instance based on its settings and category.
     * Uses the configured `idBuilder` if available.
     * If no `idBuilder` is provided, subclasses *must* override this method.
     * @returns The generated unique test ID string.
     * @throws {Error} If no `idBuilder` is provided and the method is not overridden by the subclass.
     * @protected
     */
    protected buildTestId(): string {
        if (this.idBuilder) {
            return this.idBuilder.build(this.settings, this.category);
        }
        
        // Abstract classes usually don't provide default implementation
        // but for backward compatibility and easier migration, we're providing one
        throw new Error(`buildTestId must be implemented by the subclass or an idBuilder must be provided`);
    }
    
    /**
     * Calculates a complexity score for the test case based on its settings.
     * Uses the configured `complexityBuilder` if available.
     * @returns The calculated complexity score (a number). Returns a default value of 1.0 if no `complexityBuilder` is provided.
     */
    public calculateComplexity(): number {
        if (this.complexityBuilder) {
            return this.complexityBuilder.calculate(this.settings);
        }
        
        // Return default complexity if no builder is provided
        return 1.0;
    }
    
    /**
     * Converts the test case instance into a plain JavaScript object representation.
     * Includes core properties, optional properties, and the settings object.
     * @returns An object containing the key properties of the test case.
     */
    public toObject(): Record<string, unknown> {
        return {
            name: this.name,
            prompt: this.prompt,
            objectType: this.objectType,
            category: this.category,
            complexityScore: this.complexityScore,
            successRate: this.successRate,
            mathItems: this.mathItems,
            value: this.value,
            settings: this.settings // Keep settings as a separate property
        };
    }

    // Optional validation function
    public additionalChecks?(_result: { objects: MathInput[]; testCase: TestCase<S> }): { passed: boolean; message?: string } {
        return { passed: true };
    }
    
    /**
     * Validates if this test case has required properties
     * @returns True if the test case is valid, false otherwise
     */
    public isValid(): boolean {
        return !!this.prompt && !!this.name && !!this.objectType;
    }
    
    /**
     * Gets a summary of the test case settings
     * @returns A string representation of the settings
     */
    public getSettingsSummary(): string {
        return JSON.stringify(this.settings);
    }
}



