import { CoefficientsSettings, CoefficientSettings, CoefficientsRule } from '@math/types/index';
import { CoefficientsTestCase, CoefficientTestCase } from '../cases/index';
import { CoefficientTestGenerator } from './CoefficientTestGenerator';
import { TestGenerator } from './TestGenerator';

/**
 * Generator for Coefficients test cases.
 * 
 * Creates test cases for collections of coefficients (`CoefficientsSettings`).
 * Test generation follows two main strategies:
 * 1. **Matrix Tests**: Generates combinations based on predefined `collectionCounts` (number of coefficients)
 *    and `ruleCombinations` (rules governing the relationship between coefficients, e.g., increasing, non-equal).
 * 2. **Paired Specification Tests**: Takes all unique `CoefficientTestCase` instances (generated by
 *    `CoefficientTestGenerator`), creates unique pairs of their settings, and then generates
 *    `CoefficientsTestCase` instances for these pairs, distributing them across various rule combinations.
 *    This aims to test interactions between different types of individual coefficients within a collection.
 */
export class CoefficientsTestGenerator extends TestGenerator<CoefficientsTestCase, CoefficientsSettings> {
    //**** Class Properties ****//
    /** Predefined counts for the number of coefficients in a collection. */
    private collectionCounts: number[] = [2, 5];
    /** Predefined combinations of `CoefficientsRule` to apply to the collection. */
    private ruleCombinations: CoefficientsRule[][] = [
        [], // No rules
        ['increasing'],
        ['decreasing'],
        ['neq'],
        ['increasing', 'neq'],
        ['decreasing', 'neq']
    ];
    
    /**
     * Initializes a new instance of the `CoefficientsTestGenerator`.
     * Sets the `objectType` to \'coefficients\'.
     */
    constructor() {
        super('coefficients');
    }
    
    //**** Core Generation Methods ****//
    
    /**
     * Creates a new `CoefficientsTestCase` instance with the given settings.
     * Assigns the category and calls the test case's `generate` method.
     * Overrides the abstract `createTestCase` method from the base class.
     * @param settings Optional partial `CoefficientsSettings` for the test case. Defaults to an empty object.
     * @param category Optional category label for the test case. Defaults to \'basic\'.
     * @returns The created `CoefficientsTestCase` instance.
     * @protected
     */
    protected createTestCase(settings: Partial<CoefficientsSettings> = {}, category: string = 'basic'): CoefficientsTestCase {
        const testCase = new CoefficientsTestCase(settings);
        testCase.generate();
        testCase.category = category;
        return testCase;
    }

    /**
     * Overrides the base `generateTestCase` method.
     * This ensures a non-null `CoefficientsTestCase` is always returned, as the underlying
     * `CoefficientsTestCase` constructor and `generate` method do not have validation paths
     * that would result in a null return (unlike some other `TestCase` types that validate settings).
     * @param settings Optional partial `CoefficientsSettings` for the test case. Defaults to an empty object.
     * @param category Optional category label for the test case. Defaults to \'basic\'.
     * @returns The generated `CoefficientsTestCase` instance.
     */
    public generateTestCase(settings: Partial<CoefficientsSettings> = {}, category: string = 'basic'): CoefficientsTestCase {
        return this.createTestCase(settings, category);
    }

    /**
     * Generates a matrix of basic test cases by combining all `collectionCounts` with all `ruleCombinations`.
     * For each combination, it creates a `CoefficientsTestCase` with the specified count and rules,
     * initializing the `coefficients` array in the settings with empty `CoefficientSettings` objects.
     * Category: "basic"
     * @returns An array of `CoefficientsTestCase` instances representing these basic combinations.
     * @private
     */
    private generateMatrixTests(): CoefficientsTestCase[] {
        const tests: CoefficientsTestCase[] = [];
        
        // Generate full matrix of collection counts x rule combinations
        for (const count of this.collectionCounts) {
            for (const rules of this.ruleCombinations) {
                tests.push(
                    this.generateTestCase({
                        collectionCount: count,
                        rules: rules,
                        coefficients: Array(count).fill({}) // Add empty coefficient settings with correct length
                    }, 'basic')
                );
            }
        }
        
        return tests;
    }

    //**** Specification Test Generation ****//

    /**
     * Generates `CoefficientsTestCase` instances by pairing up individual `CoefficientSettings`
     * derived from a provided list of `CoefficientTestCase` instances (specifications).
     * It creates unique pairs of these specifications and distributes them across various `CoefficientsRule` combinations.
     * This method aims to test how different types of coefficients interact within a collection of two.
     * - Ensures each specification is used at most once to form pairs.
     * - Ensures each unique pair of specifications (order-independent) is used only once.
     * - Cycles through `ruleCombinations` (excluding the last one) to apply different rules to these pairs.
     * Category: "paired specifications"
     * @param coefficientSpecs An array of `CoefficientTestCase` instances, where each represents a specific configuration for an individual coefficient.
     * @returns An array of `CoefficientsTestCase` instances, each configured with a pair of coefficient settings and a set of rules.
     */
    public generatePairedSpecificationTests(coefficientSpecs: CoefficientTestCase[]): CoefficientsTestCase[] {
        const tests: CoefficientsTestCase[] = [];
        const twoCoeffRules = this.ruleCombinations.slice(0, -1); // Skip last rule combination
        
        // Create a pool of unused specifications, tracking by test ID
        const usedSpecIds = new Set<string>();
        const unusedSpecs = coefficientSpecs.filter(spec => {
            if (usedSpecIds.has(spec.testId)) {
                return false;
            }
            usedSpecIds.add(spec.testId);
            return true;
        });

        // Create pairs from unused specifications
        const pairs: CoefficientSettings[][] = [];
        const usedPairKeys = new Set<string>();

        while (unusedSpecs.length >= 2) {
            // Take first two specs from unused pool
            const spec1 = unusedSpecs.shift()!;
            const spec2 = unusedSpecs.shift()!;
            
            // Create a unique key for this pair that's independent of order
            const settings1 = spec1.getSettings() as CoefficientSettings;
            const settings2 = spec2.getSettings() as CoefficientSettings;
            
            // Create a deterministic key for the pair
            const key1 = JSON.stringify(settings1);
            const key2 = JSON.stringify(settings2);
            const pairKey = [key1, key2].sort().join('|');
            
            // Only add if we haven't seen this pair before
            if (!usedPairKeys.has(pairKey)) {
                usedPairKeys.add(pairKey);
                pairs.push([settings1, settings2]);
            }
        }

        // Distribute each pair to exactly one rule combination
        pairs.forEach((pair, index) => {
            const ruleIndex = index % twoCoeffRules.length; // Cycle through rules
            const testCase = this.generateTestCase({
                collectionCount: 2,
                rules: twoCoeffRules[ruleIndex],
                coefficients: pair
            }, 'paired specifications');
            
            tests.push(testCase);
        });

        return tests;
    }

    //**** Main Generation Method ****//

    /**
     * Generates a comprehensive set of test cases for coefficient collections.
     * This includes:
     * 1. Basic matrix tests: Combinations of predefined collection counts and rule sets.
     * 2. Paired specification tests: Takes all unique individual coefficient configurations
     *    (from `CoefficientTestGenerator`), forms unique pairs, and tests these pairs
     *    under various collection rules.
     * Ensures uniqueness of all generated test cases based on `testId`.
     * Implements the abstract `generateAllTests` method from the base class.
     * @returns An array of unique `CoefficientsTestCase` instances.
     */
    public generateAllTests(): CoefficientsTestCase[] {
        // Generate base matrix tests
        const matrixTests = this.generateMatrixTests();

        // Get all coefficient tests using an instance of CoefficientTestGenerator
        const coefficientTestGenerator = new CoefficientTestGenerator();
        const coefficientTests = coefficientTestGenerator.generateAllTests();

        // Generate paired specification tests
        const pairedSpecTests = this.generatePairedSpecificationTests(coefficientTests);

        // Combine all tests and ensure uniqueness
        const allTests = [...matrixTests, ...pairedSpecTests];
        
        return this.validateTestUniqueness(allTests);
    }
} 



