import { ObjectType, MathObjectSettingsType } from "@math/types/index";
import { generalLatexFormat } from "../utils/formattingUtils";

/**
 * Abstract base class representing a mathematical object (e.g., Coefficient, Term, Equation).
 * 
 * Defines a common structure and generation process for all math objects.
 * Subclasses must implement the `getParts` and `formatObject` methods to define
 * their specific generation logic.
 *
 * @template S - The type of the settings object used to configure this math object.
 *               Defaults to `MathObjectSettingsType`, the union of all possible settings.
 * @template T - The type of the parameters required by the `generate` method's `getParts` step.
 *               Defaults to `void` if no parameters are needed.
 */
export abstract class MathObject<S = MathObjectSettingsType, T = void> {
    /** The specific type of this math object (e.g., "coefficient", "term"). */
    public objectType: ObjectType | null = null;
    /** The configuration settings used to generate this math object. */
    public settings: S;
    /** An array of string representations of the core components or generated values of the object. */
    public generatedItems: string[] = [];
    /** A string representation of the fully assembled object, formatted from `generatedItems`. */
    public generatedItem: string = "";
    /** The final LaTeX representation of the fully assembled object (`generatedItem`). */
    public mathItem: string = "";
    /** An array containing the LaTeX representation of each individual item in `generatedItems`. */
    public mathItems: string[] = [];

    /**
     * Constructs a new MathObject instance.
     * 
     * @param objectType - The type of math object being created.
     * @param settings - The settings configuration for this object.
     */
    constructor(objectType: ObjectType, settings: S) {
        this.objectType = objectType;
        this.settings = settings;
    }

    /**
     * Generates the mathematical object based on its settings and optional parameters.
     * This method orchestrates the generation process using the abstract `getParts` and `formatObject` methods.
     * Populates `generatedItems`, `generatedItem`, `mathItem`, and `mathItems` properties.
     * 
     * @param params - Parameters required by the specific object's `getParts` method.
     */
    public generate(params: T): void {
        // Step 1: Get the subparts (atomic: singleton array, composite: array of subparts)
        this.generatedItems = this.getParts(params);

        // Step 2: Format the object from the subparts
        this.generatedItem = this.formatObject(this.generatedItems);

        // Step 3: Format the object and subparts as LaTeX using generalLatexFormat
        this.mathItem = generalLatexFormat(this.generatedItem);
        this.mathItems = this.generatedItems.map(generalLatexFormat);
    }

    /**
     * Abstract method to be implemented by subclasses.
     * Should generate and return the core components or values of the math object as an array of strings.
     * 
     * @param params - Parameters required for generating the parts (type T).
     * @returns An array of strings representing the generated parts.
     * @protected
     */
    protected abstract getParts(params: T): string[];

    /**
     * Abstract method to be implemented by subclasses.
     * Should take the generated parts and combine/format them into a single string representation of the object.
     * 
     * @param parts - The array of strings generated by `getParts`.
     * @returns A single string representing the fully formatted object.
     * @protected
     */
    protected abstract formatObject(parts: string[]): string;
}



