import { UnitPlanData, SubunitData } from "../types/UnitPlanTypes";

// Calculate total lesson count by summing all lessonsPerSubunit values
export const calculateTotalLessonCount = (subunits: SubunitData[]): number => {
  return subunits.reduce((total, subunit) => total + subunit.lessonsPerSubunit, 0);
};

export const getEmptyUnitPlanData = (): UnitPlanData => ({
  schoolName: "",
  unitTitle: "",
  unitContent: "",
  academicYear: "",
  subject: "",
  outputMapping: "custom",
  viewingMode: "individual",
  specifiedConcepts: [],
  keyConcepts: [],
  relatedConcepts: [],
  conceptualUnderstandings: "",
  globalContext: "",
  globalContextExplanation: "",
  inquiryStatement: "",
  factualQuestions: [],
  conceptualQuestions: [],
  debatableQuestions: [],
  objectives: [],
  assessmentTitle: "",
  summativeAssessment: "",
  summativeAssessmentRelationshipDescription: "",
  assessmentTasks: [],
  assessmentType: "",
  commandTerms: [],
  individualContext: "",
  localContext: "",
  globalContextLens: "",
  atlSkills: [],
  atlStrategies: "",
  atlCards: [],
  learningExperienceCards: [],
  subunits: [],
  priorKnowledgeSubjectSpecific: [],
  priorKnowledgeLearningSkills: [],
  topicsTerminology: [],
  conceptualKnowledge: [],
  proceduralKnowledge: [],
  informalFormativeAssessment: [],
  formalFormativeAssessment: [],
  differentiationByAccess: [],
  differentiationByProcess: [],
  differentiationByProduct: [],
  resources: "",
  printedResources: [],
  digitalResources: [],
  guestsResources: [],
  communityEngagement: "",
  reflectionPriorToTeaching: "",
  reflectionDuringTeaching: "",
  reflectionAfterTeaching: "",
  reflectionFuturePlanning: "",
  contributingTeachers: [],
  lessonCount: 0,
  mypYear: 0,
  curriculumConnections: [],
});

// Keep the old function for backward compatibility if needed
export const getDefaultUnitPlanData = (): UnitPlanData => ({
  schoolName: "KMM SCHOOL",
  unitTitle: "2025–2026 m.m. UNIT PLAN",
  unitContent: "",
  academicYear: "2025-2026",
  subject: "mathematics",
  outputMapping: "custom",
  viewingMode: "individual",
  specifiedConcepts: ["Logic", "Equivalence", "Systems"],
  keyConcepts: ["Logic", "Systems"],
  relatedConcepts: ["Equivalence"],
  conceptualUnderstandings:
    "How does logic show that two things or systems in math are the same, equal, equivalent?",
  globalContext: "Scientific and technical innovation.",
  globalContextExplanation: "The nature of mathematical proof and number system.",
  inquiryStatement:
    "How does logic show that two things or systems in math are the same, equal, equivalent?",
  factualQuestions: [
    "What is a rational number?",
    "What are square and cube roots?",
    "How do we write numbers in scientific notation?",
    "What is the definition of an irrational number?",
  ],
  conceptualQuestions: [
    "What system or pattern shows how numbers change with powers and roots?",
    "How does logic help us compare and work with very big or very small numbers?",
  ],
  debatableQuestions: [
    "Is there always one correct method to prove two expressions are equal?",
    "Can two completely different-looking systems still be considered equal?",
  ],
  objectives: ["B", "C"],
  assessmentTitle: "Should the company expand? Data analysis report",
  summativeAssessment: "Assessment Title: Should the company expand? Data analysis report",
  summativeAssessmentRelationshipDescription: "",
  assessmentTasks: [],
  assessmentType: "GRASPS method.",
  commandTerms: ["apply", "explain", "justify"],
  individualContext:
    "Understanding how number systems and logical reasoning help us make personal decisions about money, time, and data.",
  localContext: "",
  globalContextLens:
    "Exploring how systems of logic and equivalence (standard form, irrational numbers) are used in global scientific innovations such as space exploration or climate modeling.",
  atlSkills: ["draw-conclusions", "interpret-data"],
  atlStrategies:
    "1. Use comparison strategies to analyze patterns between exponential and linear growth\n2. Use graphic organizers (tables, double number lines) to justify mathematical equivalence\n3. Learn how to record data systematically",
  atlCards: [],
  learningExperienceCards: [],
  subunits: getDefaultSubunits(),
  priorKnowledgeSubjectSpecific: [],
  priorKnowledgeLearningSkills: [],
  topicsTerminology: [],
  conceptualKnowledge: [],
  proceduralKnowledge: [],
  informalFormativeAssessment: [],
  formalFormativeAssessment: [],
  differentiationByAccess: [],
  differentiationByProcess: [],
  differentiationByProduct: [],
  resources: "",
  printedResources: [],
  digitalResources: [],
  guestsResources: [],
  communityEngagement: "",
  reflectionPriorToTeaching: "",
  reflectionDuringTeaching: "",
  reflectionAfterTeaching: "",
  reflectionFuturePlanning: "",
  contributingTeachers: [],
  lessonCount: calculateTotalLessonCount(getDefaultSubunits()),
  mypYear: 0,
  curriculumConnections: [],
});

const getDefaultSubunits = (): SubunitData[] => [
  {
    subunitNumber: 1,
    lessonsPerSubunit: 1,
    subunitName: "",
    content: "Introduction to rational and irrational numbers",
    priorKnowledgeSubjectSpecific: [],
    priorKnowledgeLearningSkills: [],
    topicsTerminology: [],
    conceptualKnowledge: [],
    proceduralKnowledge: [],
    successCriteria: [
      "Students distinguish between rational and irrational numbers and identify their characteristics",
    ],
    activities: "Sort rational vs. irrational numbers in groups; discuss examples",
    learningExperiences:
      "Compare and contrast activity, student-generated examples, use of diagrams and visuals",
    differentiation:
      "Provide glossary for EAL learners; color-coded number sets for visual learners.",
    summativeAssessment: "",
    interimAssessment: "",
    formativeAssessment: "",
  },
  {
    subunitNumber: 2,
    lessonsPerSubunit: 1,
    subunitName: "",
    content: "Square and cube roots; classifying numbers",
    priorKnowledgeSubjectSpecific: [],
    priorKnowledgeLearningSkills: [],
    topicsTerminology: [],
    conceptualKnowledge: [],
    proceduralKnowledge: [],
    successCriteria: ["Students can recognize square and cube numbers and their roots"],
    activities: 'Root-matching game ("Is it rational or irrational?"); classify numbers into sets',
    learningExperiences:
      "Concept journaling to record patterns and reflect on number systems; use Frayer model to define roots.",
    differentiation:
      "Scaffolded examples; tiered root challenges; visual support for abstract reasoning.",
    summativeAssessment: "",
    interimAssessment: "",
    formativeAssessment: "",
  },
  {
    subunitNumber: 3,
    lessonsPerSubunit: 1,
    subunitName: "",
    content: "Scientific notation (standard form)",
    priorKnowledgeSubjectSpecific: [],
    priorKnowledgeLearningSkills: [],
    topicsTerminology: [],
    conceptualKnowledge: [],
    proceduralKnowledge: [],
    successCriteria: ["Student can write numbers in standard and ordinary form"],
    activities: '"Convert and match" activity in pairs',
    learningExperiences:
      "Students generate inquiry questions using concepts like scale and magnitude; Simulations (distances in space) for real-world context.",
    differentiation:
      "Number line scaffold; pairing for peer support; adjusted questions for readiness.",
    summativeAssessment: "",
    interimAssessment: "",
    formativeAssessment: "",
  },
  {
    subunitNumber: 4,
    lessonsPerSubunit: 1,
    subunitName: "",
    content: "Applying scientific notation",
    priorKnowledgeSubjectSpecific: [],
    priorKnowledgeLearningSkills: [],
    topicsTerminology: [],
    conceptualKnowledge: [],
    proceduralKnowledge: [],
    successCriteria: ["Student can solve word problems using scientific notation"],
    activities: "Applied problems (populations, measurements)",
    learningExperiences:
      "Case study on real-world science problems; Visualizing the concepts using infographics to represent scale.",
    differentiation: "Sentence support for word problems; context clues added for EAL students.",
    summativeAssessment: "",
    interimAssessment: "",
    formativeAssessment: "",
  },
  {
    subunitNumber: 5,
    lessonsPerSubunit: 1,
    subunitName: "",
    content: "Indices: positive, negative, and zero",
    priorKnowledgeSubjectSpecific: [],
    priorKnowledgeLearningSkills: [],
    topicsTerminology: [],
    conceptualKnowledge: [],
    proceduralKnowledge: [],
    successCriteria: ["Student can apply index laws correctly"],
    activities: "Simplify expressions; explore exponent rules in a table",
    learningExperiences:
      'Concept-led inquiry where students ask "Why do these laws work?" and compare/contrast exponent rules.',
    differentiation:
      "Choice boards for level of challenge; color-coded exponent tables; peer explanation.",
    summativeAssessment: "",
    interimAssessment: "",
    formativeAssessment: "",
  },
  {
    subunitNumber: 6,
    lessonsPerSubunit: 1,
    subunitName: "",
    content: "Applying index laws",
    priorKnowledgeSubjectSpecific: [],
    priorKnowledgeLearningSkills: [],
    topicsTerminology: [],
    conceptualKnowledge: [],
    proceduralKnowledge: [],
    successCriteria: ["Student can simplify expressions with multiplication/division of indices"],
    activities: "Whiteboard challenges; reflection questions",
    learningExperiences:
      "Concept mapping of all exponent rules learned; students write a one-sentence summary to describe logic of equivalence.",
    differentiation:
      "Flexible grouping; scaffolding steps for rule application; sentence starters for reflection.",
    summativeAssessment: "",
    interimAssessment: "",
    formativeAssessment: "",
  },
];
