/**
 * Utilities for mapping replay item IDs to item data
 *
 * Replay files store items as numeric IDs (integers). These need to be:
 * 1. Decoded to 4-character codes (e.g., 1768712192 -> "IM2o")
 * 2. Mapped to item slugs (e.g., "IM2o" -> "iron-axe")
 * 3. Looked up in the item database
 */

import { ITEMS_DATA } from "./index";
import type { ItemData } from "@/types/items";

/**
 * Decode Warcraft III object ID integer into its 4-character string
 *
 * Warcraft 3 stores object IDs as 32-bit integers where each byte represents
 * a character in the 4-character code (little-endian).
 *
 * @param value - Numeric object ID from replay
 * @returns 4-character code (e.g., "IM2o") or null if invalid
 */
export function decodeObjectId(value: number): string | null {
  if (typeof value !== "number" || Number.isNaN(value) || value === 0) {
    return null;
  }

  let result = "";
  let remaining = value;

  // Extract 4 bytes (characters) from the integer (little-endian)
  for (let i = 0; i < 4; i++) {
    const charCode = remaining & 0xff;
    result = String.fromCharCode(charCode) + result;
    remaining = remaining >>> 8;
  }

  return result.trim() ? result : null;
}

/**
 * Mapping from raw 4-character item codes to item slugs
 *
 * This mapping is automatically generated by the data generation script:
 * scripts/data/generate/generate-item-code-mapping.mjs
 *
 * Example: "IM2o" -> "iron-axe"
 */
export const RAW_ITEM_CODE_TO_SLUG: Record<string, string> = {
  I052: "armor-salve",
  I054: "hypnosis-salve",
  I055: "poison-salve",
  I056: "speed-salve",
  I057: "alligator-gold",
  I058: "blink",
  "IM0{": "panther-fang",
  "IM0}": "hunter-s-trophy",
  "IM0|": "hunter-s-trophy",
  "IM0~": "blow-gun",
  IM02: "food-slot",
  IM03: "scavenged-mushroom",
  IM04: "happy-food-supplies",
  IM05: "materials-slot",
  IM06: "paws-of-bear-s-greed",
  IM07: "stashed-raw-meat",
  IM08: "eat-raw-meat",
  IM09: "robe-of-the-magi",
  IM0a: "venom-fang",
  IM0b: "troll-protector",
  IM0c: "a-thief-s-pocket",
  IM0d: "philosopher-s-stone",
  IM0e: "acid-bomb",
  IM0f: "makruru-cuirass",
  IM0g: "makrura-carapace",
  IM0h: "makrura-claw",
  IM0i: "anabolic-boots",
  IM0y: "paws-of-bear-s-greed",
  IM0j: "anabolic-potion",
  IM0k: "anti-magic-potion",
  IM0l: "armory-kit",
  IM0m: "athelas-seed",
  IM0n: "coconut",
  IM0o: "banana",
  IM0p: "battle-armor",
  IM0q: "battle-axe",
  IM0r: "battle-gloves",
  IM0s: "battle-shield",
  IM0t: "bear-skin-boots",
  IM0u: "boots-of-bear-s-tenacity",
  IM0v: "bear-skin-coat",
  IM0w: "coat-of-bear-s-terrifying-presence",
  IM0x: "bear-skin-gloves",
  IM0z: "bee-hive",
  "IM1!": "leaf-of-blue-herb",
  "IM1{": "gem-of-knowledge",
  "IM1}": "hatchery-kit",
  "IM1|": "hydra-scale-coat",
  "IM1~": "hawk-egg",
  IM10: "bone",
  IM11: "bone-boots",
  IM12: "bone-coat",
  IM13: "bone-gloves",
  IM14: "bone-shield",
  IM15: "clay-ball",
  IM16: "clay-explosion",
  IM17: "cloak-of-flames",
  IM18: "necromancer-s-cloak",
  IM19: "cloak-of-frost",
  IM1a: "cloak-of-healing",
  IM1b: "cloak-of-mana",
  IM1c: "cooked-meat",
  IM1d: "cure-potion",
  IM1e: "dark-spear",
  IM1f: "chameleon-hatchet",
  IM1g: "chameleon-hatchet",
  IM1h: "chameleon-hatchet",
  IM1i: "dark-thistles",
  IM1y: "flint",
  IM1j: "disc0-duck-s-pinion-of-fire",
  IM1k: "disc0-duck-s-pinion-of-pain",
  IM1l: "disc0-duck-s-pinion-of-shadow",
  IM1m: "disease-potion",
  IM1n: "drunk-s-potion",
  IM1o: "elk-hide",
  IM1p: "elk-skin-boots",
  IM1q: "elk-skin-coat",
  IM1r: "elk-skin-gloves",
  IM1s: "emp",
  IM1t: "ensnare-trap-kit",
  IM1u: "essence-of-bees",
  IM1v: "fervor-potion",
  IM1w: "fire-bomb",
  IM1x: "camp-fire-kit",
  IM1z: "forge-kit",
  "IM2!": "healing-potion",
  "IM2{": "poison",
  "IM2}": "twin-island-potion",
  "IM2|": "poison-spear",
  "IM2~": "mixing-pot-kit",
  IM20: "horn-of-the-mammoth",
  IM21: "mage-s-grimoire",
  IM22: "hunting-net",
  IM23: "hydra-claws",
  IM24: "magefist",
  IM25: "hydra-fins",
  IM26: "hydra-hint",
  IM27: "scale",
  IM28: "iron-axe",
  IM29: "iron-boots",
  IM2a: "iron-coat",
  IM2b: "iron-gloves",
  IM2c: "iron-ingot",
  IM2d: "iron-shield",
  IM2e: "iron-spear",
  IM2f: "bear-hide",
  IM2g: "wolf-hide",
  IM2h: "living-clay",
  IM2i: "mage-fire-kit",
  IM2y: "oracle-potion",
  IM2j: "mage-masher",
  IM2k: "magic",
  IM2l: "honeycomb",
  IM2m: "magic-seed",
  IM2n: "magic-palm-tree-seed",
  IM2o: "mana-crystal",
  IM2p: "mana-potion",
  IM2q: "medallion-of-courage",
  IM2r: "medallion-of-courage",
  IM2s: "mud-hut-kit",
  IM2t: "mushroom",
  IM2u: "nether-potion",
  IM2v: "net",
  IM2w: "omnicure-potion",
  IM2x: "omnitower-kit",
  IM2z: "leaf-of-orange-herb",
  "IM3{": "teleport-beacon-kit",
  "IM3}": "medalion-of-the-thief",
  "IM3|": "tent-kit",
  "IM3~": "thistles",
  IM31: "river-root",
  IM32: "river-stem",
  IM33: "healing-salve",
  IM34: "scroll-of-cyclone",
  IM35: "scroll-of-entangling-roots",
  IM36: "scroll-of-fire-ball",
  IM37: "scroll-of-living-dead",
  IM38: "scroll-of-stone-shield",
  IM39: "scroll-of-haste",
  IM3a: "scroll-of-tsunami",
  IM3b: "basic-shield",
  IM3c: "smoke-bomb",
  IM3d: "smoke-house-kit",
  IM3e: "stone-spear",
  IM3f: "spirit-of-darkness",
  IM3g: "spirit-ward-kit",
  IM3h: "leaf-of-native-herb",
  IM3i: "leaf-of-exotic-herb",
  IM3y: "storage-hut-kit",
  IM3j: "lesser-essence",
  IM3k: "greater-essence",
  IM3l: "spirit-of-water",
  IM3m: "spirit-of-wind",
  IM3n: "steel-axe",
  IM3o: "steel-boots",
  IM3p: "steel-coat",
  IM3q: "steel-gloves",
  IM3r: "steel-ingot",
  IM3s: "steel-shield",
  IM3t: "steel-spear",
  IM3u: "stick",
  IM3w: "stone",
  IM3x: "stone-axe",
  IM3z: "tannery-kit",
  "IM4!": "tinder",
  IM40: "transport-ship-kit",
  IM41: "troll-hut-kit",
  IM42: "ultra-poison",
  IM43: "ultra-poison-spear",
  IM44: "witch-doctors-hut-kit",
  IM45: "wolf-skin-boots",
  IM46: "boots-of-wolfs-stamina",
  IM47: "wolf-skin-coat",
  IM48: "wolf-skin-gloves",
  IM49: "claws-of-wolf-s-bloodlust",
  IM4a: "coat-of-wolf-s-voracity",
  IM4b: "workshop-kit",
  IM4c: "hunter-s-trophy",
  IM4d: "hunter-s-trophy",
  IM4e: "hunter-s-trophy",
  IM4f: "empowered-necromancer-s-cloak",
  IM4g: "iron-staff",
  IM4h: "battle-staff",
  IM4i: "conducting-rod",
  IM4j: "staff-of-wisdom",
  IM4k: "staff-of-wisdom",
  IM4l: "poison-thistles",
  IM4n: "tidebringer",
  IM4o: "right-mammoth-horn",
  IM4p: "mammoth-boots",
  IM4s: "arms-slot",
  IM4t: "scroll-slot",
};

/**
 * Get item by replay ID (numeric ID from game replay)
 *
 * Converts a numeric replay ID to an item by:
 * 1. Decoding the numeric ID to a 4-character code
 * 2. Looking up the code in RAW_ITEM_CODE_TO_SLUG to get the item slug
 * 3. Looking up the item by slug using getItemById
 *
 * @param replayId - Numeric item ID from replay metadata
 * @returns ItemData if found, undefined otherwise
 */
export function getItemByReplayId(replayId: number): ItemData | undefined {
  if (!replayId || replayId === 0) {
    return undefined;
  }

  // Step 1: Decode numeric ID to 4-character code
  const itemCode = decodeObjectId(replayId);
  if (!itemCode) {
    // Debug: log if decode fails
    if (process.env.NODE_ENV === "development") {
      console.debug("[getItemByReplayId] Failed to decode replay ID:", replayId);
    }
    return undefined;
  }

  // Step 2: Map code to item slug
  const itemSlug = RAW_ITEM_CODE_TO_SLUG[itemCode];
  if (!itemSlug) {
    // Debug: log if mapping not found
    if (process.env.NODE_ENV === "development") {
      console.debug(
        "[getItemByReplayId] No mapping found for code:",
        itemCode,
        "from replay ID:",
        replayId
      );
    }
    return undefined;
  }

  // Step 3: Get item by slug
  const item = ITEMS_DATA.find((item) => item.id === itemSlug);
  if (!item && process.env.NODE_ENV === "development") {
    console.debug("[getItemByReplayId] Item not found for slug:", itemSlug, "from code:", itemCode);
  }
  return item;
}

/**
 * Get items by replay IDs (array of numeric IDs from game replay)
 * Filters out zeros and invalid IDs
 *
 * @param replayIds - Array of numeric item IDs from replay metadata
 * @returns Array of ItemData objects for valid items
 */
export function getItemsByReplayIds(replayIds: number[]): ItemData[] {
  if (!replayIds || replayIds.length === 0) {
    return [];
  }

  const items: ItemData[] = [];
  for (const replayId of replayIds) {
    if (replayId && replayId !== 0) {
      const item = getItemByReplayId(replayId);
      if (item) {
        items.push(item);
      }
    }
  }
  return items;
}
